INSERT INTO database."CLINICAL_CENTERS" ("NAME", "STREET", "BUILDING_NUMBER", "LOCALITY", "POSTAL_CODE")
	VALUES ('Test clinical center', 'Test street', '1a', 'Test locality', '01-234');
	
INSERT INTO database."PATIENTS" ("INITIALS", "BIRTH_DATE", "HOSPITALISATION_DATE", "CKRT_START_DATE", "WEIGHT", "HEIGHT", "CLINICAL_CENTER_ID")
	VALUES ('TT', NOW(), NOW(), NOW(), 10, 30, 1);
	
INSERT INTO database."DOCTORS" ("FIRST_NAME", "LAST_NAME", "IS_DATA_ADMINISTRATOR", "PASSWORD", "EMAIL")
	VALUES ('Johnny', 'Bravo', 0, '0123456789', 'johnny@bravo.com');

INSERT INTO database."CLINICAL_DATA" ("PATIENT_ID", "CLINICAL_DATA_TYPE_CODE", "CLINICAL_DATA_TYPE_DISCRIMINATOR", "DATA_COLLECTION_DATE", "DOCTOR_ID")
	VALUES (1, 25, 'C', NOW(), 1);
	
INSERT INTO database."CLINICAL_DATA_PARAMETERS_VALUES" VALUES (1, 25, 'C', '2023-01-07', 155, 0, NULL, 'Nadciśnienie tętnicze...');
	
INSERT INTO database."CLINICAL_DATA_WITH_PARAMETERS_VIEW" VALUES (1, 25, 'C', '2023-01-07', 0, 153, 'ECMO', 1, 1, '', 'ECMO ...');
INSERT INTO database."CLINICAL_DATA_WITH_PARAMETERS_VIEW" VALUES (1, 25, 'C', '2023-01-07', 0, 154, 'Bezmocz / skąpomocz', 1, 1, '', 'Bezmocz / skąpomocz ...');

SELECT * FROM database."CLINICAL_DATA_WITH_PARAMETERS_VIEW";