SELECT * FROM database."CLINICAL_DATA_WITH_PARAMETERS_VIEW";


-- FUNCTIONS
CREATE OR REPLACE FUNCTION database."VALIDATE_DATE_FOR_CLINICAL_DATA_PARAMETERS_FUNC"()
	RETURNS TRIGGER AS $$
BEGIN
	INSERT INTO database."CLINICAL_DATA_PARAMETERS_VALUES"
		("PATIENT_ID", "CLINICAL_DATA_TYPE_CODE", "CLINICAL_DATA_TYPE_DISCRIMINATOR",
		"CLINICAL_DATA_COLLECTION_DATE", "PARAMETER_CODE", "NUMERIC_VALUE", "TEXT_VALUE",
		"DESCRIPTION")
	VALUES (NEW."PATIENT_ID", NEW."CLINICAL_DATA_TYPE_CODE", NEW."CLINICAL_DATA_TYPE_DISCRIMINATOR",
		   NEW."DATA_COLLECTION_DATE", NEW."PARAMETER_CODE", NEW."NUMERIC_VALUE", NEW."TEXT_VALUE",
		   NEW."PARAMETER_VALUE_DESCRIPTION");
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- TRIGGERS
CREATE OR REPLACE TRIGGER "VALIDATE_DATE_FOR_CLINICAL_DATA_PARAMETERS_TRG"
	INSTEAD OF INSERT ON database."CLINICAL_DATA_WITH_PARAMETERS_VIEW"
	FOR EACH ROW
EXECUTE FUNCTION database."VALIDATE_DATE_FOR_CLINICAL_DATA_PARAMETERS_FUNC"()
