SELECT
	s."PATIENT_ID"
	, s."DOCTOR_ID"
	, s."PROCEDURE_TYPE_CODE"
	, s."PROCEDURE_TYPE_DISCRIMINATOR"
	, s."PROCEDURE_DATE"
	, s."SESSION_TYPE_CODE"
	, s."SESSION_TYPE_DISCRIMINATOR"
	, s."ORDINAL_NUMBER"
	, val."PARAMETER_CODE"
	, p."NAME" AS "PARAMETER_NAME"
	, p."DATA_TYPE"
	, p."IS_PARAMETER_REGISTRATION_SUGGESTED"
	, val."NUMERIC_VALUE"
	, val."TEXT_VALUE"
	, val."DESCRIPTION"
	, s."IS_DRAFT_VERSION"
FROM database."TYPES" AS t
	LEFT JOIN database."PROCEDURES_SESSIONS" as s ON (t."TYPE_CODE" = s."SESSION_TYPE_CODE"
													 AND t."TYPE_DISCRIMINATOR" = s."SESSION_TYPE_DISCRIMINATOR")
	LEFT JOIN database."PARAMETERS" AS p ON (t."TYPE_CODE" = p."TYPE_CODE" AND t."TYPE_DISCRIMINATOR" = p."TYPE_DISCRIMINATOR")
	LEFT JOIN database."PROCEDURES_SESSIONS_PARAMETERS_VALUES" AS val ON (p."TYPE_CODE" = val."SESSION_TYPE_CODE"
																	  AND p."TYPE_DISCRIMINATOR" = val."SESSION_TYPE_DISCRIMINATOR"
																	  AND p."PARAMETER_CODE" = val."PARAMETER_CODE")
WHERE t."TYPE_CODE" = 2 AND t."TYPE_DISCRIMINATOR" = 'S';

CREATE OR REPLACE VIEW database."CLINICAL_DATA_WITH_PARAMETERS_VIEW"
AS
	SELECT
		cd."PATIENT_ID"
		, cd."CLINICAL_DATA_TYPE_CODE"
		, cd."CLINICAL_DATA_TYPE_DISCRIMINATOR"
		, cd."DATA_COLLECTION_DATE"
		, cd."IS_DRAFT_VERSION"
		, p."PARAMETER_CODE"
		, p."NAME" AS "PARAMETER_NAME"
		, p."DATA_TYPE"
		, val."NUMERIC_VALUE"
		, val."TEXT_VALUE"
		, val."DESCRIPTION" AS "PARAMETER_VALUE_DESCRIPTION"
	FROM database."TYPES" AS t
		LEFT JOIN database."CLINICAL_DATA" AS cd ON (t."TYPE_CODE" = cd."CLINICAL_DATA_TYPE_CODE"
													AND t."TYPE_DISCRIMINATOR" = cd."CLINICAL_DATA_TYPE_DISCRIMINATOR")
		LEFT JOIN database."PARAMETERS" AS p ON (t."TYPE_CODE" = p."TYPE_CODE"
												 AND t."TYPE_DISCRIMINATOR" = p."TYPE_DISCRIMINATOR")
		LEFT JOIN database."CLINICAL_DATA_PARAMETERS_VALUES" AS val ON (cd."PATIENT_ID" = val."PATIENT_ID"
																	   AND cd."CLINICAL_DATA_TYPE_CODE" = val."CLINICAL_DATA_TYPE_CODE"
																	   AND cd."CLINICAL_DATA_TYPE_DISCRIMINATOR" = val."CLINICAL_DATA_TYPE_DISCRIMINATOR"
																	   AND cd."DATA_COLLECTION_DATE" = val."CLINICAL_DATA_COLLECTION_DATE")
	WHERE t."TYPE_DISCRIMINATOR" = 'C' AND (val."NUMERIC_VALUE" IS NOT NULL OR val."TEXT_VALUE" IS NOT NULL);